# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_num', models.TextField(max_length=10)),
                ('street_name1', models.TextField(max_length=255)),
                ('street_name2', models.TextField(blank=True, max_length=255)),
                ('street_name3', models.TextField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('date_begin', models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0), null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='energymanager.Address')),
            ],
        ),
    ]
